FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY data/raw ./data/raw

EXPOSE 8001
CMD uvicorn app.etl.service:app --host 0.0.0.0 --port ${PORT:-8001}
